version: '2'
services:
  nginx-react:
    container_name: frenchToastWeeklyReport
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    environment:
      NODE_ENV: production