version: '2'
services:
  nginx-react:
    container_name: frenchToastWeeklyReport
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    networks:
      - back
networks:
  back:
    external:
      name: french-toast-weekly-report-2-api_back
